services:
  engine:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_USER: ${DB_USER_NAME}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
